# -*- coding: utf-8 -*-
"""flag_detecting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UF5P5TB3TsQIku5p5QZKZkzdzg8yoVHR
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics

import ultralytics
from ultralytics import YOLO
from IPython.display import display, Image
ultralytics.checks()

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="1sZbqhgComuKT6ZW7NTG")
project = rf.workspace("student-twmiq").project("flags-d59gk")
version = project.version(2)
dataset = version.download("yolov8")

model = YOLO("yolov8n.pt")
results = model.train(data="/content/flags-2/data.yaml", epochs=60, imgsz=640)

Image(filename='/content/runs/detect/train3/confusion_matrix.png', width=600)

Image(filename='/content/runs/detect/train3/results.png', width=600)

model_bset = YOLO('/content/runs/detect/train3/weights/best.pt')
matrices = model_bset.val(data='/content/flags-2/data.yaml')

predict = model_bset.predict(source='/content/flags-2/test/images', conf=0.25, save=True)

import glob
from IPython.display import Image, display

for image_path in glob.glob('/content/runs/detect/predict/*.jpg'):
      display(Image(filename=image_path, width=600))
      print("\n")